// Growable typed arrays for the milling moves (spec §3.3). One entry per straight chord, in
// execution order. Pure: no DOM; runs in the worker and in Node.
export const K_RAPID = 0;       // G0
export const K_FEED = 1;        // G1/G2/G3 (arcs arrive as chords)
export const K_CFEED = 2;       // feed generated by a drilling cycle
export const K_CRAPID = 3;      // rapid generated by a drilling cycle

export function createMoves(capacity = 4096) {
  return {
    count: 0,
    cap: capacity,
    pos: new Float32Array(capacity * 6),
    kind: new Uint8Array(capacity),
    line: new Uint32Array(capacity),
    row: new Uint16Array(capacity),
    wofs: new Uint8Array(capacity),
    seconds: new Float32Array(capacity),
  };
}

function grow(m) {
  const cap = m.cap * 2;
  const next = (Ctor, old, per = 1) => { const a = new Ctor(cap * per); a.set(old); return a; };
  m.pos = next(Float32Array, m.pos, 6);
  m.kind = next(Uint8Array, m.kind);
  m.line = next(Uint32Array, m.line);
  m.row = next(Uint16Array, m.row);
  m.wofs = next(Uint8Array, m.wofs);
  m.seconds = next(Float32Array, m.seconds);
  m.cap = cap;
}

// a and b are {x, y, z}; seconds may be NaN (not timeable), which is kept as NaN.
export function pushMove(m, a, b, kind, line, row, wofs, seconds) {
  if (m.count === m.cap) grow(m);
  const i = m.count, p = i * 6;
  m.pos[p] = a.x; m.pos[p + 1] = a.y; m.pos[p + 2] = a.z;
  m.pos[p + 3] = b.x; m.pos[p + 4] = b.y; m.pos[p + 5] = b.z;
  m.kind[i] = kind;
  m.line[i] = line;
  m.row[i] = row;
  m.wofs[i] = wofs;
  m.seconds[i] = seconds;
  m.count = i + 1;
  return i;
}

// Exact-length copies, so the worker can transfer the buffers without sending unused capacity.
export function finishMoves(m) {
  const n = m.count;
  return {
    count: n,
    pos: m.pos.slice(0, n * 6),
    kind: m.kind.slice(0, n),
    line: m.line.slice(0, n),
    row: m.row.slice(0, n),
    wofs: m.wofs.slice(0, n),
    seconds: m.seconds.slice(0, n),
  };
}

// CSR map from source line to the moves it produced (a line inside a subprogram called three times
// owns three sets of moves). offsets has lines + 2 entries so line L's moves are
// moves[offsets[L] .. offsets[L + 1]).
export function buildLineIndex(moves, lineCount) {
  const offsets = new Uint32Array(lineCount + 2);
  for (let i = 0; i < moves.count; i++) offsets[moves.line[i] + 1]++;
  for (let l = 1; l < offsets.length; l++) offsets[l] += offsets[l - 1];
  const fill = offsets.slice();
  const list = new Uint32Array(moves.count);
  for (let i = 0; i < moves.count; i++) list[fill[moves.line[i]]++] = i;
  return { offsets, moves: list };
}

export function movesOfLine(index, line) {
  if (!index || line < 0 || line + 1 >= index.offsets.length) return [];
  return Array.from(index.moves.subarray(index.offsets[line], index.offsets[line + 1]));
}
